### ISSUE TITLE
mpi_launcher.sh overrides user MODULEPATH

### ISSUE THREAD

**Issue by besserox** [ULHPC/launcher-scripts#4]
The [example MPI launcher](https://github.com/ULHPC/launcher-scripts/blob/devel/bash/MPI/mpi_launcher.sh) overrides the user `MODULEPATH`. This is annoying if the user has its own modules. This is because of line 46:

```
    .  /etc/profile
```

I would suggest to not source `/etc/profile` and just do `bash -l` instead. This has the benefit that it shows the same behavior between interactive and passive session.

What do you think?

**Comment by fgeorgatos** [comment]
+1 ;-)

that has been exactly the argument in favour of `bash -l`, since the beginning of time!

more generally, the fact that sourcing `/etc/profile` creates such an issue, 
is a sign of a common pesty bug like: https://github.com/plabrop/bic/issues/2

btw. 
that repo has the original `.spec` on which 500+ Bright clusters rely on. It should be fine ;-)
